<h2>Editar Tarea</h2>
<div class="container">
	<div class="col-md-6 mx-auto">
		<form class="form form-group" action="<?php echo APP_URL."categorias/actualizar"; ?>" method="POST">
			
			<div class="form-group">
				<label for="nombre">Nombre</label>
				<input type="text" name="nombre" class="form-control" value="<?php echo $this->categoria['nombre'] ?>">
			</div>

			<button type="submit" class="btn btn-primary">Guardar</button>
		</form>
	</div>
</div>